### PR TITLE
Add DataLoader 'after' argument and always wrap in promises

### PR DESCRIPTION
**Pull request by theojulienne**
As I've been looking at widening the usage of the `IOPromise::DataLoader`, I found a couple of things that were a bit awkward.

Firstly, it's really common to want to short circuit inside an `attr_async`, and this wasn't previously supported because it wasn't returning a promise all the time. By wrapping the lambda execution inside a `#then` block, we can allow returning either a literal or a Promise, just like in a promise chain:
```ruby
attr_async :sometimes_a_thing, -> do
  return false if not_a_thing? # before this PR, this would raise an error
  do_some_async_op(...)
end
```

Another common situation is that you have a few `attr_async` items, with some dependency between them. This is currently awkward because you can reference the attribute using the helper sync method (which calls `#sync` for you), but that will resolve the promise inappropriately by nesting calls to `#sync` on a not-yet-resolved promise:
```ruby
attr_async :object_to_load, -> { ... }
attr_async :contents_of_object, -> { object_to_load.load_contents_of_object } # fail: forces the object to sync rather than chaining promises
```

The user can be clever, and use the `async_` version and create a promise chain. This works, but is a bit more complex because it forces the long form:
```ruby
attr_async :object_to_load, -> { ... }
attr_async :contents_of_object, -> { async_object_to_load.then { object_to_load.load_contents_of_object } }
```

But if multiple objects are needed, this starts getting more verbose quickly:
```ruby
attr_async :object_to_load, -> { ... }
attr_async :viewer, -> { ... }
attr_async :contents_of_object, -> do
 Promise.all([async_object_to_load, async_viewer]).then { object_to_load.load_contents_of_object_for(viewer) }
end
```

This PR allows a simpler declarative form that automates this dependency, conveniently ensuring the promise is resolved by the time it executes, thereby allowing referencing dependent promises by their sync helper (which is fine by this point, because the promise is already fulfilled).
```ruby
# with a single dependency
attr_async :object_to_load, -> { ... }
attr_async :contents_of_object, after: :object_to_load, then: -> do
 object_to_load.load_contents_of_object
end

# with multiple dependencies
attr_async :object_to_load, -> { ... }
attr_async :viewer, -> { ... }
attr_async :contents_of_object, after: [:object_to_load, :viewer], then: -> do
 object_to_load.load_contents_of_object_for(viewer)
end
```

Annoyingly, it's not possible to pass in an unnamed argument after keyword arguments, so the lambda needs to be specified with one (`:then` is what I used here, since it's the term we use normally for generating a promise chain).

/cc @mclark for thoughts

### CODE REVIEW

**Comment by mclark** [comment]
I think this makes sense, but it mostly makes me start thinking about linting and validates we can add that might make sense before everyone jumps on this bandwagon. Here are some ideas:

* `AttributeNotUsedError` if an attribute is defined but not used in the UI in a given run. As attributes are eagerly loaded, we should ensure we only declare those that we will always need. This begs the question of how to handle conditionally used attributes though 🤔  Am I over thinking this? Here's where my mind went:

```ruby
attr_async :object_to_load, -> { ... }
attr_async :viewer, -> { ... }
attr_async :contents_of_object, after: [:object_to_load, :viewer], then: -> do
 object_to_load.load_contents_of_object_for(viewer)
end
attr_async :conditional_feature, after: :contents_of_object, if: -> { contents_of_object.active? }
```

* `EarlySyncError` if sync is called when a promise chain is being resolved

As we are essentially working on "Promises 2.0" from GitHub's perspective maybe this is an opportunity to learn from our mistakes and get a bit more strict, conditionally at least. Maybe these errors could just be raised in development, I don't know.

Looking at that conditional attributes thing I think we need to be very careful how far we go down this path. Even in this PR it's starting to look a bit like a DSL and that is definitely something we should avoid. Keeping things as boring vanilla Ruby as possible is a good thing.

I think I need to cogitate about this PR a bit more before I'm certain it's a good path to go down. As you know, adding "sugar" like this should be very carefully considered before proceeding.

**Comment by theojulienne** [comment]
> I think I need to cogitate about this PR a bit more before I'm certain it's a good path to go down. As you know, adding "sugar" like this should be very carefully considered before proceeding.

:+1: :heart: Thank you for the care here, I agree this makes sense to consider carefully.

> Looking at that conditional attributes thing I think we need to be very careful how far we go down this path. Even in this PR it's starting to look a bit like a DSL and that is definitely something we should avoid. Keeping things as boring vanilla Ruby as possible is a good thing.

Yea, this current PR felt very similar to me to the level of declarative model building in Rails' `before_action` and friends, though that's not to say that Rails doesn't also verge on a DSL :joy: Where the line in the sand is, is a good question.

> AttributeNotUsedError if an attribute is defined but not used in the UI in a given run.

This is really interesting, but potentially difficult to implement because we don't have a firm way of knowing when things are "done" being used, the only points we really get to add instrumentation are before and after data loading. I guess it would be some sort of instrumentation and Rack middleware that work together and are probably only installed during dev/test? 🤔 

> This begs the question of how to handle conditionally used attributes though 🤔

Just to explicitly list the alternative, without the validation this can be done with `after` and a short circuit, which I actually find quite easy to read/reason about:
```ruby
attr_async :conditional_feature, after: :contents_of_object, then: -> do
  return unless contents_of_object.active?
  # <expensive load here>
end
```

Of course, the downside being that you can't validate if it was actually called/referenced if you're just no-oping it like this, because you no longer declaratively say whether it is expected to be used or not 🤔 

> EarlySyncError if sync is called when a promise chain is being resolved

I was thinking this too. It's still a little tricky to implement this because the resolution can depend on `#then` blocks that are run async, and since `#sync` on the data loader itself may not ever be used (it could be chained into an arbitrary promise using `async_attributes`). I wonder if this is something that a rubocop linter would be better at, ensuring sync methods are not called from within `attr_async` blocks (perhaps unless they were defined in the `after:`). 🤔 I guess it would be _possible_ to do validation in the promise chain, though not pretty.

**Comment by mclark** [comment]
I have thought about this some more and it's just not sitting right with me. @theojulienne would you be opposed to putting this change on hold until we have a proven need? I think I'd rather pursue a way to disallow forcing a sync when already resolving a Promise. It doesn't address the verbose `Promise.all` stuff you mentioned above, but it at least prevents from accidentally introducing blocking IO where there shouldn't be any. Something like this (pseudocode):

```ruby
class Promise
  def self.resolving(&block)
    @resolving = true
    block.call
    @resolving = false
  end

  def self.resolving?
    @resolving
  end
  
  def sync
    raise InvalidSyncError if Promise.resolving?
    Promise.resolving do
      if pending?
        # etc...
      end
    end
  end
end
```

With some sort of guard like this in place we can ensure folks never call `sync` explicitly except when not already resolving. But I'm not super familiar with how Promise.rb works so maybe this sort of thing isn't feasible?

**Comment by theojulienne** [comment]
> would you be opposed to putting this change on hold until we have a proven need?

:+1: I'm happy to leave this here and see how it feels after some more code adopts the pattern.

> With some sort of guard like this in place we can ensure folks never call sync explicitly except when not already resolving.

I wonder if it's plausible in a large code base to guarantee this (though obviously it's ideal), given there could be very nested calls to unrelated promises (behind non-promise code paths) that may not be immediately feasible to wire up to the promise chain. 🤔 

In the short term, I think we can probably protect against some of this by linting on names in the same DataLoader being synced, since that information should be available to rubocop.

**Pull request closed without merging**
